
import type { Metadata } from "next";

import "./globals.css";

import Navbar from "../component/organisms/Navbar";
import Footer from "../component/organisms/Footer";



export const metadata: Metadata = {
  title: "Ini app saya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />       
      </body>
    </html>
  );
}
